### ISSUE TITLE
CVM call to remove cookie box results in thrown exception

### ISSUE THREAD

**Issue by BrettHemes-3M** [joergen7/dinner#2]
Error:

    snip ... {'function not exported',[{gen_pnet,ls_place,[compartment,{net_state,#{cash_box ...

The cvm example, upon trying to remove a cookie box, tries to call `ls_place` which doesn't exist.  Replacing this with a call to `gen_pnet:get_ls` fixes the issue.

Fix implemented in #1

**Comment by joergen7** [comment]
I can reproduce this error, thanks for pointing it out.

**Comment by joergen7** [comment]
Solved by your pull request.
